import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/context/AuthProvider";
import ReactQueryProvider from "@/components/context/ReactQueryProvider";
import Header from "@/components/modules/Header";
import Footer from "@/components/modules/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Torino Project",
  description: "Generated by Hamed Foroughi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={inter.className}>
        <ReactQueryProvider>
          <AuthProvider>
            <Header />
            {children}
            <Footer />
            </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
